# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIvvGGxJViq-kkZ7ohZhE41XWMoZiash
"""

!mkdir Orders

!pip install pyunpack
!pip install patool

from pyunpack import Archive

Archive('Orders.7z').extractall('/content')

# importing element tree
import xml.etree.ElementTree as ET 

# Pass the path of the xml document 
tree = ET.parse('orders.xml') 

# get the parent tag 
root = tree.getroot() 

# print the root (parent) tag along with its memory location 
print(root)

# print the attributes of the first tag  
print(root[0].attrib) 
print(root[0].get('book'))

len(root)

#for ele in root:
print(root[500].attrib)

from queue import PriorityQueue

map = {}
for ele in root:
    if ele.get('book') not in map.keys():
        map[ele.get('book')] = {'SELL':PriorityQueue(), 'BUY':PriorityQueue()}
    if(ele.get('operation')):
        map[ele.get('book')][ele.get('operation')].put({'price':ele.get('price'),'volume':ele.get('volume'),'orderId':ele.get('orderId')})

